---
platform: linux
image: docker:///emccmd/rackhd-cpi
inputs:
- name: scaleio-sdc-bosh-release
- name: scaleio-sdc-release-version-semver
outputs:
- name: promote
run:
  path: scaleio-sdc-bosh-release/ci/tasks/promote-candidate.sh
params:
  S3_ACCESS_KEY_ID:       replace-me
  S3_SECRET_ACCESS_KEY:   replace-me
  SDC_RELEASE_NAME:       replace-me
