---
platform: linux
image: docker:///emccmd/rackhd-cpi
inputs:
- name: rexray-bosh-release
- name: rexray-release-version-semver
outputs:
- name: promote
run:
  path: rexray-bosh-release/ci/tasks/promote-rexray-candidate.sh
params:
  S3_ACCESS_KEY_ID:       replace-me
  S3_SECRET_ACCESS_KEY:   replace-me
  REXRAY_RELEASE_NAME:    replace-me
