---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: {{docker_repo}}
    insecure_registries: [{{docker_registry}}]
inputs:
- name: rexray-bosh-release
- name: rexray-release-version-semver
outputs:
- name: promote
run:
  path: rexray-bosh-release/ci/tasks/promote-rexray-candidate.sh
params:
  REXRAY_RELEASE_NAME:    replace-me
  S3_ACCESS_KEY_ID:       replace-me
  S3_SECRET_ACCESS_KEY:   replace-me
