---
groups:
- name: rexray-scaleio
  jobs:
  - scaleio-volman-acceptance
  - promote-scaleio-sdc-candidate
  - promote-rexray-candidate

jobs:
- name: scaleio-volman-acceptance
  serial: true
  plan:
  - aggregate:
    - {trigger: true,       get: scaleio-sdc-bosh-release}
    - {trigger: true,       get: rexray-bosh-release}
    - {trigger: true,       get: volman}
  - task: vats
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: {{docker_repo}}
          insecure_registries: [{{docker_registry}}]
      inputs:
      - name: scaleio-sdc-bosh-release
      - name: rexray-bosh-release
      - name: volman
      run:
        path: rexray-bosh-release/ci/tasks/vats.sh
      params:
        BOSH_DIRECTOR_PUBLIC_IP:            {{bosh_director_public_ip}}
        BOSH_PASSWORD:                      {{bosh_password}}
        BOSH_USER:                          {{bosh_user}}
        DEPLOYMENT_NAME:                    {{deployment_name}}
        DEPLOYMENT_PASSWORD:                {{deployment_password}}
        DEPLOYMENT_PRIVATE_KEY:             {{deployment_private_key}}
        FAKE_VOLUME_NAME:                   {{vats_fake_volume_name}}
        REXRAY_RELEASE_NAME:                {{rexray_release_name}}
        SCALEIO_ENDPOINT:                   {{scaleio_endpoint}}
        SCALEIO_INSECURE:                   {{scaleio_insecure}}
        SCALEIO_MDM_IPS:                    {{scaleio_mdm_ips}}
        SCALEIO_PASSWORD:                   {{scaleio_password}}
        SCALEIO_PROTECTION_DOMAIN_ID:       {{scaleio_protection_domain_id}}
        SCALEIO_PROTECTION_DOMAIN_NAME:     {{scaleio_protection_domain_name}}
        SCALEIO_SDC_RELEASE_NAME:           {{scaleio_sdc_release_name}}
        SCALEIO_STORAGE_POOL_ID:            {{scaleio_storage_pool_id}}
        SCALEIO_STORAGE_POOL_NAME:          {{scaleio_storage_pool_name}}
        SCALEIO_SYSTEM_ID:                  {{scaleio_system_id}}
        SCALEIO_USER_ID:                    {{scaleio_user_id}}
        SCALEIO_USERNAME:                   {{scaleio_username}}
        SCALEIO_VERSION:                    {{scaleio_version}}
        VSPHERE_VM_IP:                      {{vsphere_vm_ip}}

- name: promote-scaleio-sdc-candidate
  serial: true
  plan:
  - aggregate:
    - {trigger: true,  passed: [scaleio-volman-acceptance], get: scaleio-sdc-bosh-release}
    - {trigger: false,                                      get: rexray-bosh-release}
    - {trigger: false,                                      get: scaleio-sdc-release-version-semver, params: {bump: major}}
  - task: promote-scaleio-sdc-release
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: {{docker_repo}}
          insecure_registries: [{{docker_registry}}]
      inputs:
      - name: scaleio-sdc-bosh-release
      - name: scaleio-sdc-release-version-semver
      - name: rexray-bosh-release
      outputs:
      - name: promote
      run:
        path: rexray-bosh-release/ci/tasks/promote-scaleio-sdc-candidate.sh
      params:
        GITHUB_USER:                  {{github_user}}
        GITHUB_PASSWORD:              {{github_password}}
        S3_ACCESS_KEY_ID:             {{s3_access_key_id}}
        S3_SECRET_ACCESS_KEY:         {{s3_secret_access_key}}
        SCALEIO_SDC_RELEASE_NAME:     {{scaleio_sdc_release_name}}
  - put: scaleio-sdc-release-version-semver
    params: {file: scaleio-sdc-release-version-semver/number}

- name: promote-rexray-candidate
  serial: true
  plan:
  - aggregate:
    - {trigger: true,   passed: [scaleio-volman-acceptance], get: rexray-bosh-release}
    - {trigger: false,                                       get: rexray-release-version-semver,  params: {bump: major}}
  - task: promote-rexray-release
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: {{docker_repo}}
          insecure_registries: [{{docker_registry}}]
      inputs:
      - name: rexray-bosh-release
      - name: rexray-release-version-semver
      outputs:
      - name: promote
      run:
        path: rexray-bosh-release/ci/tasks/promote-rexray-candidate.sh
    params:
      GITHUB_USER:          {{github_user}}
      GITHUB_PASSWORD:      {{github_password}}
      S3_ACCESS_KEY_ID:     {{s3_access_key_id}}
      S3_SECRET_ACCESS_KEY: {{s3_secret_access_key}}
      REXRAY_RELEASE_NAME:  {{rexray_release_name}}
  - put: rexray-release-version-semver
    params: {file: rexray-release-version-semver/number}

resources:
- name: scaleio-sdc-bosh-release
  type: git
  source:
    uri: https://{{github_user}}:{{github_password}}@github.com/EMC-Dojo/ScaleIO-SDC-Bosh-Release.git
    branch: master

- name: rexray-bosh-release
  type: git
  source:
    uri: https://{{github_user}}:{{github_password}}@github.com/EMC-Dojo/rexray-boshrelease.git
    branch: master

- name: scaleio-sdc-bosh-release-out
  type: git
  source:
    uri: https://{{github_user}}:{{github_password}}@github.com/EMC-Dojo/ScaleIO-SDC-Bosh-Release.git
    branch: master

- name: rexray-bosh-release-out
  type: git
  source:
    uri: https://{{github_user}}:{{github_password}}@github.com/EMC-Dojo/rexray-boshrelease.git
    branch: master

- name: volman
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/volman

- name: rexray-release-version-semver
  type: semver
  source:
    key:               release-current-version
    bucket:            {{s3_rexray_semver_bucket_name}}
    access_key_id:     {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}

- name: scaleio-sdc-release-version-semver
  type: semver
  source:
    key:               release-current-version
    bucket:            {{s3_scaleio_sdc_semver_bucket_name}}
    access_key_id:     {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}
